# Generated by Django 3.2.21 on 2023-10-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_hobby_interest_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hobbies',
            new_name='hobby',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='interests',
            new_name='interest',
        ),
    ]
