# Generated by Django 3.2.21 on 2023-10-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20231007_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='recidence',
            new_name='residence',
        ),
    ]
