# Generated by Django 3.2.21 on 2023-10-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='selectedDate',
            field=models.DateField(default='2023-01-14'),
        ),
    ]
