# Generated by Django 3.2.21 on 2023-10-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20231024_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='buttonType',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
