# Generated by Django 3.2.21 on 2023-10-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_userresponse_buttontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
