# Generated by Django 3.2.21 on 2023-11-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_userrequest_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
