# Generated by Django 3.2.21 on 2023-11-05 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_userresponse_is_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='is_processed',
        ),
    ]
