# Generated by Django 3.2.21 on 2023-11-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_remove_userresponse_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='situation',
            field=models.BooleanField(default=False),
        ),
    ]
