# Generated by Django 3.2.21 on 2023-11-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_userrequest_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
