# Generated by Django 3.2.23 on 2023-12-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_chatmessage_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='item_images/フリー女.jpeg', null=True, upload_to='item_images/'),
        ),
    ]
