# Generated by Django 3.2.23 on 2023-12-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detail',
            field=models.TextField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='item_images/フリー女.jpeg', null=True, upload_to='event_images/'),
        ),
    ]
