# Generated by Django 3.2.23 on 2023-12-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_auto_20231227_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='item_images/フリー女.jpeg', null=True, upload_to='item_images/'),
        ),
    ]
