# Generated by Django 3.2.23 on 2023-12-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_userrequest_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='eventId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='userData',
            field=models.DateField(default='2023-01-14', null=True),
        ),
    ]
