# Generated by Django 3.2.23 on 2023-12-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_auto_20231230_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='eventId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.event'),
        ),
    ]
