name: Deploy to EC2 on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF
          cd Schedule-Link
          git pull
          echo 'DJANGO_ENV=${{ secrets.DJANGO_ENV }}' > .env
          echo 'MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}' >> .env
          echo 'MYSQL_USER=${{ secrets.MYSQL_USER }}' >> .env
          echo 'MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}' >> .env
          echo 'MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}' >> .env
          echo 'HOST=${{ secrets.HOST }}' >> .env
          echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' >> .env
          docker-compose up -d
        EOF
